1. Create a 2D Numpy array with shape (3, 3) containing random integers
between 1 and 20.

In [10]:
import numpy as np
a = np.random .randint(1, 20, (3,3))
print (a)

[[17  3 18]
 [ 4 10 15]
 [ 9 11  1]]


2. Write a NumPy program to create a 5x5 array with random values and find
the minimum and maximum values for each row.

In [70]:
import numpy as np
empty_a = np.empty((5, 5), dtype=int)
print("Array:\n", empty_a)

for i in range(empty_a.shape[0]): 
    row_min = np.min(empty_a[i])
    row_max = np.max(empty_a[i])
    print(f"Row {i}: min = {row_min:}, max = {row_max:}")

Array:
 [[-1934656808       32762    95532880         636           6]
 [          0    95532880         636           6     6619204]
 [   95532880         636           7   942749030           0]
 [          0    95533264         636    95533264         636]
 [   95533264         636           0           0   929391205]]
Row 0: min = -1934656808, max = 95532880
Row 1: min = 0, max = 95532880
Row 2: min = 0, max = 942749030
Row 3: min = 0, max = 95533264
Row 4: min = 0, max = 929391205


3. Write a NumPy program to create a random vector of size 10 and sort it.

In [145]:
import numpy as np
vec = np.random.randint(1,11, size=10)   
print(f"Random Vector:\n {vec}")

sorted_vec = np.sort(vec)
print(f"\nSorted vector:\n{sorted_vec}")



Random Vector:
 [7 7 8 7 4 9 7 3 9 1]

Sorted vector:
[1 3 4 7 7 7 7 8 9 9]


4. Write a NumPy program to find the most frequent value in an array.

In [61]:
import numpy as np
a=np.array([1,6,3,4,8,8,3,8,9])
most_frequent = np.bincount(a).argmax()
print("The most frequent number is:", most_frequent)



The most frequent number is: 8


5. Replace all even numbers in the 2D array with 0.

In [88]:
import numpy as np

a = np.array([[1,2, 5], [3, 4, 6]])
print("Array:\n", a)
a[a% 2 == 0] = 0
print(f"\nArray after replacing even numbers with 0:\n", a)


Array:
 [[1 2 5]
 [3 4 6]]

Array after replacing even numbers with 0:
 [[1 0 5]
 [3 0 0]]


6. Apply the square root function to each element of the 1D array.

In [89]:
import numpy as np
a = np.array([1, 4, 9, 16, 25, 36])

print("Array:", a)

sqrt_a = np.sqrt(a)
print("Square root array:", sqrt_a)


Array: [ 1  4  9 16 25 36]
Square root array: [1. 2. 3. 4. 5. 6.]


7. Write a NumPy program to create a 3x3 array with random values and
subtract the mean of each row from each element.

In [105]:
import numpy as np
a= np.empty((3, 3), dtype=int)
print("Random 3x3 array:\n", a)
row_means = a.mean(axis=1)
print("Row means:", row_means)
result=a - row_means
print("Resulting array after subtracting row means:\n", result) 

Random 3x3 array:
 [[1 6 3]
 [4 1 8]
 [3 8 9]]
Row means: [3.33333333 4.33333333 6.66666667]
Resulting array after subtracting row means:
 [[-2.33333333  1.66666667 -3.66666667]
 [ 0.66666667 -3.33333333  1.33333333]
 [-0.33333333  3.66666667  2.33333333]]


8. Create a 1D array containing the first 20 odd numbers.

In [100]:
import numpy as np
a_odd= np.arange(1,40,2)
print("Odd numbers between 1 and 40:\n\n", a_odd)

Odd numbers between 1 and 40:

 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


9. Write a NumPy program to create a 5x5 array with random values and find
the second-largest value in each column.

In [137]:
import numpy as np

a = np.empty((5, 5), dtype=int)
print("Array:\n", a)


sorted_a = np.sort(a, axis=0)

second_largest = sorted_a[-2, :]

print("\nSecond largest value in each column:\n", second_largest)


Array:
 [[         0          0          0          0          0]
 [  83838504        636         64          0    6619204]
 [1634087778  808935735  842347314  811885414  808804663]
 [1647338853  878916193  878915639  828793649  960061793]
 [1647458660 1714709349  929457457  962736948  962672945]]

Second largest value in each column:
 [1647338853  878916193  878915639  828793649  960061793]


10. Write a NumPy program to create a 4x4 array with random values and find
the sum of each row.

In [144]:
import numpy as np
a = np.random.rand(4, 4)
print("Array:\n", a)

row_sums = np.sum(a, axis=1)

print("\nSum of each row:\n", row_sums)



Array:
 [[0.76306506 0.86140666 0.32669323 0.23248645]
 [0.55390243 0.57428408 0.34763833 0.3246013 ]
 [0.33296079 0.40655598 0.54922418 0.81227478]
 [0.02186242 0.56920137 0.96625772 0.5921989 ]]

Sum of each row:
 [2.18365139 1.80042615 2.10101573 2.14952042]
